# Generated by Django 5.2.4 on 2025-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('color', models.CharField(choices=[('R', 'Red'), ('A', 'Apricot'), ('B', 'Black'), ('S', 'Silver'), ('T', 'Tan')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breed', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='costumer/')),
            ],
        ),
        migrations.CreateModel(
            name='PetKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pet-knowledge/')),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='pets/')),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('type', models.CharField(choices=[('DF', 'Dog food'), ('CF', 'Cat food'), ('T', 'Toy'), ('C', 'Costume')], max_length=2)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product-detail/')),
                ('sku', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('vaccinated', models.CharField(max_length=3)),
                ('dewormed', models.CharField(max_length=3)),
                ('cert', models.CharField(max_length=100)),
                ('microchip', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('additional_info', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sellers/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
